services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: shallabuf
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: shallabuf
    ports:
      - "5432:5432" # PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nats:
    image: nats:latest
    ports:
      - "4222:4222" # Client Port
    command: ["-js"]

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # MinIO Console
    volumes:
      - minio_data:/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000" # Rocket launch
    env_file:
      - .env
    depends_on:
      - postgres
      - nats
      - minio
      - scheduler

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile.scheduler
    env_file:
      - .env
    depends_on:
      - postgres
      - nats

volumes:
  postgres_data:
  minio_data:
