global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']

  - job_name: 'postgres'
    metrics_path: /metrics
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    metrics_path: /metrics
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'nats'
    metrics_path: /metrics
    static_configs:
      - targets: ['nats:8222']
