//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use super::sea_orm_active_enums::NodeContainerType;
use super::sea_orm_active_enums::Visibility;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "nodes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub publisher_name: String,
    pub description: Option<String>,
    pub config: Json,
    pub container_type: NodeContainerType,
    pub tags: Vec<String>,
    pub versions: Vec<String>,
    pub visibility: Visibility,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::pipeline_nodes::Entity")]
    PipelineNodes,
}

impl Related<super::pipeline_nodes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PipelineNodes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
