//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "pipeline_nodes_connections")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub from_node_id: Uuid,
    pub to_node_id: Uuid,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::pipeline_nodes::Entity",
        from = "Column::FromNodeId",
        to = "super::pipeline_nodes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PipelineNodes2,
    #[sea_orm(
        belongs_to = "super::pipeline_nodes::Entity",
        from = "Column::ToNodeId",
        to = "super::pipeline_nodes::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PipelineNodes1,
}

impl ActiveModelBehavior for ActiveModel {}
